# Generated by Django 5.2.8 on 2025-11-20 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="County",
            fields=[
                ("county_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=50)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "unique_together": {("name", "province")},
            },
        ),
        migrations.CreateModel(
            name="AgricultureSales",
            fields=[
                ("sale_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.PositiveIntegerField()),
                ("product_type", models.CharField(max_length=100, null=True)),
                (
                    "sales_volume",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "sales_value",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.county"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CountyDemographics",
            fields=[
                ("demo_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.PositiveIntegerField()),
                ("population_total", models.BigIntegerField(null=True)),
                (
                    "urbanization_rate",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "unemployment_rate",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("migrant_workers", models.BigIntegerField(null=True)),
                (
                    "social_security_rate",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.county"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfrastructureService",
            fields=[
                ("infra_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.PositiveIntegerField()),
                (
                    "pct_village_with_hard_road",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "pct_village_with_electricity",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "broadband_coverage",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "water_supply_coverage",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "sanitation_coverage",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.county"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CountyEconomy",
            fields=[
                ("econ_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.PositiveIntegerField()),
                (
                    "gdp_total",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "fiscal_revenue",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "per_capita_income",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.county"
                    ),
                ),
            ],
            options={
                "unique_together": {("county", "year")},
            },
        ),
    ]
