# Generated by Django 5.2.8 on 2025-11-20 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_usertablepermission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPromptConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_schema",
                    models.TextField(help_text="数据库表结构说明，用于AI理解数据库"),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        default="你是一个专业 SQL 帮助助手。", help_text="AI系统提示词"
                    ),
                ),
                (
                    "user_prompt_template",
                    models.TextField(
                        default="你是一个 SQL 助手，请严格根据下面的数据库结构为用户生成正确的 SQL。\n\n{table_schema}\n\n用户的问题是：\n【{question}】\n\n请输出：\n1. 一条可执行的 SQL 查询语句（只要 SQL，本行不要自然语言）\n2. 对查询结果的自然语言解释（简短）\n\n格式要求：\n\nSQL:\n<你的 SQL>\n\nExplanation:\n<自然语言说明>",
                        help_text="用户提示词模板，{table_schema}和{question}会被替换",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Prompt配置",
                "verbose_name_plural": "AI Prompt配置",
            },
        ),
    ]
